### ISSUE TITLE
Analysis of RNA-seq data with variancePartition, also valid for few samples? 

### ISSUE THREAD

**Issue by tim-meese** [DiseaseNeuroGenomics/variancePartition#2]
Hello authors of variancePartition

Is an analysis with variancePartition valid for experiments with a low sample size? In my specific case, I have only six samples. 

Thanks for the feedback. 

With kind regards
Tim

**Comment by GabrielHoffman** [comment]
That is on the low side, so the ability the estimate the random effects is pretty low.  `limma` might be a better choice here
